name: setup-and-test
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
        with:
          node-version: 18.x
          cache: npm
      - run: make setup
      - run: make test
      - run: make lint     
